# Downloading body pose (MPI) model...
wget -c "https://www.uio.no/ritmo/english/research/labs/fourms/software/musicalgesturestoolbox/mgt-python/pose-models/body25/pose_iter_584000.caffemodel" -P "$1" --no-check-certificate 
# Download finished.