# Downloading body pose (BODY_25) model... 
wget -P "$1" "https://www.uio.no/ritmo/english/research/labs/fourms/software/musicalgesturestoolbox/mgt-python/pose-models/body25/pose_iter_584000.caffemodel" --no-check-certificate 
# Download finished.