# Downloading body pose (COCO) model...
wget -c "https://www.uio.no/ritmo/english/research/labs/fourms/software/musicalgesturestoolbox/mgt-python/pose-models/coco/pose_iter_440000.caffemodel" -P "coco/" --no-check-certificate
# Download finished.
