# Downloading body pose (MPI) model...
wget -P "$1" "https://www.uio.no/ritmo/english/research/labs/fourms/software/musicalgesturestoolbox/mgt-python/pose-models/mpi/pose_iter_160000.caffemodel" --no-check-certificate 
# Download finished.